// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykuyhrhzpuqeubbaqrdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdXlocmh6cHVxZXViYmFxcmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Njc0NTAsImV4cCI6MjA3MTU0MzQ1MH0.6YkvVOmu4cQxISpmgyZa6sZjDH-1-i78QiZ7spxVsMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});